### ISSUE TITLE
FactCheck Explorer cookie

### ISSUE THREAD

**Issue by ageil** [MartinoMensio/MisinfoMe_datasets#2]
I'm trying to download all ClaimReviews from Google FactCheck Explorer using this tool, but need some more guidance on obtaining and setting the GOOGLE_FACTCHECK_EXPLORER_COOKIE.

Can you please clarify in simple steps how to use the web inspector to find this cookie in the .env file? And where exactly to set it to download the ~28000 items?

(I was already granted access to FactCheck Explorer.)

**Comment by MartinoMensio** [comment]
Hi @ageil . Just to be clear, I am not providing in this repository any of the collected content and any cookie. You are responsible for the usage of the data that you retrieve on your own.

With this premise, cookies are sensitive data that store your login on your browser and in this case authorise your access to the FactCheck Explorer (see https://en.wikipedia.org/wiki/HTTP_cookie ). To inspect your cookies you can look at several guides like https://stackoverflow.com/questions/4423061/view-http-headers-in-google-chrome and when you have it simply you have to create a file at the path `{REPOSITORY_ROOT_DIRECTORY}/.env` with the following content:

```
GOOGLE_FACTCHECK_EXPLORER_COOKIE={PUT_YOUR_FACTCHECK_EXPLORER_COOKIE}
```

**Comment by ageil** [comment]
Thanks @MartinoMensio! I don't usually work with web-scraping, so recognizing what to look for in the web inspector and how exactly to format it into the .env file did the trick!
